sudo: false

language: nodejs

services:
    - docker

notifications:
    email:
        on_success: never
        on_failure: never

install:
    # - docker pull banacorn/agda
    # - docker run banacorn/agda agda -V
    - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

branches:
    only:
        # - spec
        - travis


env:
    global:
        - APM_TEST_PACKAGES="agda-mode language-agda"

    matrix:
        - ATOM_CHANNEL=stable
