before_install:
    - which npm
    - which nvm

script:
    - docker pull banacorn/agda:$AGDA_VERSION
    - docker run banacorn/agda:$AGDA_VERSION agda -V
    # - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

language: node_js
node_js: stable

git:
    depth: 10

sudo: false

os:
    # - linux
    - osx

env:
    # dependencies for Atom
    global:
        - APM_TEST_PACKAGES="agda-mode language-agda"

    matrix:
        - AGDA_VERSION=2.4.2.5
        # - AGDA_VERSION=2.4.2.4
        # - AGDA_VERSION=2.4.2.3
        # - AGDA_VERSION=2.4.2.2

services:
    - docker
    # - nvm

addons:
    apt:
        packages:
            # for Atom
            - build-essential
            - git
            - libgnome-keyring-dev
            - fakeroot
