script:
    - docker pull banacorn/agda
    - docker run banacorn/agda agda -V
    - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

language: node_js

git:
    depth: 10

sudo: false

os:
    - linux
    - osx

env:
    global:
        - APM_TEST_PACKAGES="agda-mode language-agda"

    matrix:
        - ATOM_CHANNEL=stable

services:
    - docker

addons:
    apt:
        packages:
            - build-essential
            - git
            - libgnome-keyring-dev
            - fakeroot
#
#
# sudo: false
#
# language: nodejs
#
# services:
#     - docker
#
# notifications:
#     email:
#         on_success: never
#         on_failure: never
#
# install:
#     # - docker pull banacorn/agda
#     # - docker run banacorn/agda agda -V
#     - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
#
# branches:
#     only:
#         # - spec
#         - travis
#
#
# os:
#   - linux
#
# env:
#     global:
#         - APM_TEST_PACKAGES="agda-mode language-agda"
#
#     matrix:
#         - ATOM_CHANNEL=stable
